// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDLOynk3zTvPwMKt1hgmrdqIpFr9jXX0',
    appId: '1:878742612590:web:d79c3ecadbfc75b1a9947f',
    messagingSenderId: '878742612590',
    projectId: 'apeat-4b0af',
    authDomain: 'apeat-4b0af.firebaseapp.com',
    storageBucket: 'apeat-4b0af.appspot.com',
    measurementId: 'G-QM4Y827GN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwohToj0K5WARO_6_4MSeneb1MWY71gdA',
    appId: '1:878742612590:android:43915ae6cdd3d63ea9947f',
    messagingSenderId: '878742612590',
    projectId: 'apeat-4b0af',
    storageBucket: 'apeat-4b0af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA91gCrlN9lD6DsvUv_WzJ8FS2wurca3pc',
    appId: '1:878742612590:ios:49d5ec4a6a87c40ba9947f',
    messagingSenderId: '878742612590',
    projectId: 'apeat-4b0af',
    storageBucket: 'apeat-4b0af.appspot.com',
    iosBundleId: 'com.example.apeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA91gCrlN9lD6DsvUv_WzJ8FS2wurca3pc',
    appId: '1:878742612590:ios:49d5ec4a6a87c40ba9947f',
    messagingSenderId: '878742612590',
    projectId: 'apeat-4b0af',
    storageBucket: 'apeat-4b0af.appspot.com',
    iosBundleId: 'com.example.apeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYDLOynk3zTvPwMKt1hgmrdqIpFr9jXX0',
    appId: '1:878742612590:web:6832243808cbd7bea9947f',
    messagingSenderId: '878742612590',
    projectId: 'apeat-4b0af',
    authDomain: 'apeat-4b0af.firebaseapp.com',
    storageBucket: 'apeat-4b0af.appspot.com',
    measurementId: 'G-F25MGNV44H',
  );
}
